spring.application.name=spring-ai-library-core
telegram.repository.url=http://localhost:8081

# Redis 공통 접속 정보
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# 일반 캐시(@Cacheable) 전용 Redis DB 번호
spring.data.redis.cache.database=35

# 벡터 캐시(RedisVectorStore) 전용 Redis DB 번호
spring.data.redis.database=39

# ===============================
# Datasource (HikariCP)
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

# ===============================
# HikariCP pool settings
# ===============================
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# Spring AI
# ===============================
spring.ai.openai.base-url=https://emb.java21.net
spring.ai.openai.api-key=dummy
spring.ai.openai.embedding.options.model=bge-m3
spring.ai.vectorstore.pgvector.embedding-model-bean-name=openAiEmbeddingModel
spring.ai.openai.chat.enabled=false

# ===============================
# Google gemini
# ===============================
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.7
spring.ai.google.genai.project-id=unused

# ===============================
# Ollama
# ===============================
spring.ai.ollama.base-url=http://ollama.java21.net
spring.ai.ollama.chat.options.model=qwen2.5:latest
spring.ai.ollama.chat.options.temperature=0.3
spring.ai.ollama.embedding.enabled=false
spring.ai.ollama.chat.options.duration=300
spring.ai.ollama.init.timeout=300

spring.ai.selected-model=ollama

# ===============================
# Auto-configuration Exclusions
# ===============================
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration

# 정보나루 api
data4-library.api.url= http://data4library.kr/api/
data4-library.api.service-key=${DATA_LIBRARY_SERVICE_KEY}

# RabbitMQ 설정
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=2
spring.rabbitmq.listener.simple.default-requeue-rejected=false
# ===============================
# RabbitMQ Listener Concurrency
# ===============================
spring.rabbitmq.listener.simple.concurrency=3
spring.rabbitmq.listener.simple.max-concurrency=5
spring.rabbitmq.listener.simple.prefetch=1

# ===============================
# cross-encoder (cohere Reranker API) 관련
# ===============================
cohere.api.key=${COHERE_API_KEY}
cohere.api.url=https://api.cohere.com/v1/rerank
cohere.api.rank.k=20


# ===============================
# VectorBookSearchRepository 관련
# ===============================
vector.similarity.threshold=0.50

# ===============================
# semantic cache 관련
# ===============================
semantic.cache.similarity.threshold=0.87
semantic.cache.similarity.ttl=1800

# ===============================
# RrfBookReranker 관련
# ===============================
rrf.business.filter.k=30
rrf.score.threshold=0.013

# ===============================
# HybridSearch 관련
# ===============================
hybrid.search.candidate=100

# ===============================
# Virtual Threads
# ===============================
spring.threads.virtual.enabled=true