spring.application.name=spring-ai-library-core

# Redis \uACF5\uD1B5 \uC811\uC18D \uC815\uBCF4
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# \uC77C\uBC18 \uCE90\uC2DC(@Cacheable) \uC804\uC6A9 Redis DB \uBC88\uD638
spring.data.redis.cache.database=35

# \uBCA1\uD130 \uCE90\uC2DC(RedisVectorStore) \uC804\uC6A9 Redis DB \uBC88\uD638
spring.data.redis.database=39